version: "3"
services:
  reverseproxy:
      image: jesusrodrc/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: jesusrodrc/udacity-restapi-user
    environment:
      POSGRESS_USERNAME: $POSGRESS_USERNAME
      POSGRESS_PASSWORD: $POSGRESS_PASSWORD 
      POSGRESS_DB: $POSGRESS_DB 
      POSGRESS_HOST: $POSGRESS_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: $URL
  backend-feed:
    image: jesusrodrc/udacity-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSGRESS_USERNAME: $POSGRESS_USERNAME
      POSGRESS_PASSWORD: $POSGRESS_PASSWORD 
      POSGRESS_DB: $POSGRESS_DB 
      POSGRESS_HOST: $POSGRESS_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: $URL
  frontend:
    image: jesusrodrc/udacity-frontend:local
    ports:
      - "8100:80"
